name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [v1.x]
        os: [macOS-10.15, macOS-latest, ubuntu-latest, windows-2019]

    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/deno
          key: ${{ runner.os }}-${{ matrix.deno }}-${{ hashFiles('**/*.ts') }}

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print info
        run: |
          deno info

      - name: Run tests
        run: |
          deno test --unstable -A --coverage=./cov

      - name: Generate lcov
        shell: bash
        run: |
         deno coverage ./cov/ --lcov > cov.lcov
         deno coverage ./cov/

      - name: Remove coverage report
        shell: bash
        if: matrix.os != 'ubuntu-latest'
        run: |
          rm -rf ./cov/
          rm cov.lcov
